platform :ios, '12.4'

use_frameworks!

target 'LivActiv' do
  # Pods for LivActiv
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  # ...add any library need headers
end 